export const STATUS_OPTIONS: Array<string> = [
  'FUTURE_INTERESTED',
  'HIGH_PRIORITY',
  'LOW_PRIORITY',
  'NEED_CLARIFICATION',
  'NOT_ELIGIBLE',
  'NOT_INTERESTED',
  'ON_PROCESS',
];

export enum ClientStage {
  NEW_LEAD = "NEW_LEAD",
  FIRST_TALK_DONE = "FIRST_TALK_DONE",
  FOLLOWING_UP = "FOLLOWING_UP",
  CLIENT_INTERESTED = "CLIENT_INTERESTED",
  ACCOUNT_OPENED = "ACCOUNT_OPENED",
  NO_RESPONSE_DORMANT = "NO_RESPONSE_DORMANT",
  NOT_INTERESTED_DORMANT = "NOT_INTERESTED_DORMANT",
  RISKY_CLIENT_DORMANT = "RISKY_CLIENT_DORMANT",
  HIBERNATED = "HIBERNATED",
}

export enum LeadStage {
  NEW_LEAD = 'NEW_LEAD',
  FIRST_TALK_DONE = 'FIRST_TALK_DONE',
  FOLLOWING_UP = 'FOLLOWING_UP',
  CLIENT_INTERESTED = 'CLIENT_INTERESTED',
  ACCOUNT_OPENED = 'ACCOUNT_OPENED',
  NO_RESPONSE_DORMANT = 'NO_RESPONSE_DORMANT',
  NOT_INTERESTED_DORMANT = 'NOT_INTERESTED_DORMANT',
  RISKY_CLIENT_DORMANT = 'RISKY_CLIENT_DORMANT',
  HIBERNATED = 'HIBERNATED',
}

export enum LeadStatus {
  PENDING = 'PENDING',
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  ON_HOLD = 'ON_HOLD',
  CLOSED = 'CLOSED',
  LOST = 'LOST',
}

// New Stage Filter classification (separate from pipeline stage)
export enum LeadStageFilter {
  FUTURE_INTERESTED = 'FUTURE_INTERESTED',
  HIGH_PRIORITY = 'HIGH_PRIORITY',
  LOW_PRIORITY = 'LOW_PRIORITY',
  NEED_CLARIFICATION = 'NEED_CLARIFICATION',
  NOT_ELIGIBLE = 'NOT_ELIGIBLE',
  NOT_INTERESTED = 'NOT_INTERESTED',
  ON_PROCESS = 'ON_PROCESS',
}

export type ClientStatus = LeadStage;

export const STAGE_OPTIONS: Array<LeadStage | string> = [
  'NEW_LEAD','FIRST_TALK_DONE','FOLLOWING_UP','CLIENT_INTERESTED','ACCOUNT_OPENED','NO_RESPONSE_DORMANT','NOT_INTERESTED_DORMANT','RISKY_CLIENT_DORMANT','HIBERNATED',
];